### ISSUE TITLE
Idle CPU usage + Failure of io_uring backend

### ISSUE THREAD

**Issue by Bob-van** [mookums/zzz#14]
Is there any plan of reducing idle CPU usage?
It seem to be consuming a lot of CPU just silently waiting.

**Comment by mookums** [comment]
Which aio backend are you using and what platform are you on?

**Comment by Bob-van** [comment]
busy_loop tested on windows

**Comment by mookums** [comment]
This is expected as the busy loop works just by polling the nonblocking socket. If you tried it on another platform with a supported backend, such as Linux (io_uring, epoll) or Mac (kqueue), you wouldn't see this behavior.

Windows will be getting a specific aio backend (IOCP) sometime soon.

**Comment by Bob-van** [comment]
Also i have encountered a runtime error of ArgumentsInvalid in Tardy when using zzz.
The error occurs in init() inside `tardy-0.1.0/src/aio/io_uring.zig`:
```
uring.* = try std.os.linux.IoUring.init(
   std.math.ceilPowerOfTwoAssert(u16, size),
   base_flags,
);
```
The dropping values are:
- entries: 2048
- base_flags: 4352

Drops in zzz 2.0 and master branches (didn't find newer Tardy version than 1.0).
Run at Ubuntu x86_64 (RYZEN CPU if it helps).
If you need anything else i would be happy to help.

**Comment by Bob-van** [comment]
Also looking at the code, it would be nice to add a errdefers in specific parts of initialization to clean up if error occurs, because it memory leaks.
In most scenarios it does not matter since most applications would want to terminate on error in zzz initialization, but for the possibility of needing it it might be a good practice.

**Comment by mookums** [comment]
1. Could you post the code snippet that you used to initialize the runtime? I'm able to use 2048 entries just fine without throwing an error. Those `base_flags` are normal as they correspond to the flags that we are using when creating the uring.

2. Yeah, there are some places where it would be nice to have (like in `serve`). A lot of the internal omission of `errdefer` is just because some failures are unrecoverable and should be handled through termination.

**Comment by Bob-van** [comment]
`Tardy(.auto)`
`Server(.plain)`

Inicialization:
```
tardy = try Tardy.init(.{
   .allocator = allocator,
   .threading = .auto,
});
router = Router.init(allocator);
```
```
try tardy.entry(
   &router,
   struct {
      fn entry(rt: *Runtime, r: *const Router) !void {
            var server = Server.init(.{ .allocator = rt.allocator });
            server.bind(host, port) catch |err| {
            std.debug.print("Bind failed with: {s}\n", .{@errorName(err)});
            return err;
         };
         server.serve(r, rt) catch |err| {
            std.debug.print("Serve failed with: {s}\n", .{@errorName(err)});
            return err;
         };
      }
   }.entry,
   {},
   struct {
      fn exit(rt: *Runtime, _: void) !void {
         Server.clean(rt) catch |err| {
            std.debug.print("Clean failed with: {s}\n", .{@errorName(err)});
            return err;
         };
      }
   }.exit,
);
```

There is some logging just to determinate whether it failed, but it gets never triggered.
The entry() itself errors.

2. It makes sense that there are points of no recovery, its true somewhere `errdefer` could be added, but makes sense its not worth while rn.

**Comment by Bob-van** [comment]
It should be correct based on examples, i have no idea why it fails.
Also on windows, running busy_loop it works fine.
The error it returns based on `IoUring.zig` is supposed to mean:
```
// The resv array contains non-zero data, p.flags contains an unsupported flag,
// entries out of bounds, IORING_SETUP_SQ_AFF was specified without IORING_SETUP_SQPOLL,
// or IORING_SETUP_CQSIZE was specified but linux.io_uring_params.cq_entries was invalid:
```

**Comment by mookums** [comment]
What version of Ubuntu and what kernel version are you on? I'll see if I can reproduce this tomorrow on an Ubuntu VM. Can you try the `.epoll` backend to see if you get the same issue?

**Comment by Bob-van** [comment]
I am doing some more digging, i might have an idea why it could be failing

**Comment by Bob-van** [comment]
OK, got some more information and its interesting:
- I was building from source (not using zig package manager, i know the manager uses source too, i just hand-rolled my own build), so i obviously tought the mistake would be in my build. Tested, the mistake is not there, the build with zig package manager fails too, both behave exactly the same ...
- `.epoll` is working sometimes, did some more tests, in like 80% of cases it double frees during initialization, but only rarely it aborts the program, even when it double frees. When the program runs it serves my website correctly.
- `.io_uring` is failing completely, there is no inconsistency in the error it gives, still the same as above.
- `.busy_loop` seems to be working on windows 100% of the time, on the Ubuntu server it behaves same as `.epoll`

I will be doing some more examination, but this seems bizarre.
Btw. i am using zig-0.13, as is instructed in the readme!

**Comment by mookums** [comment]
1. The issue with the `io_uring` backend is that the flags used require a newer kernel than `5.15`. There are more details [here in the kernel docs](https://man7.org/linux/man-pages/man2/io_uring_setup.2.html) but `COOP_TASKRUN` requires `5.19` and `SINGLE_ISSUER` requires `6.0`. It's throwing the error because these flags are invalid. I'll make a note in [tardy](https://github.com/mookums/tardy) for this and make the flags conditional on kernel version.

2. I'm unable to reproduce the issue with the `epoll` and `busy_loop` double free issue. I'm able to reproduce something similar if I use an allocator that isn't thread-safe. Could you try using a threadsafe allocator and if it happens again, could you post the stack trace so we could figure out where this is happening?

**Comment by Bob-van** [comment]
I have been using `var gpa = std.heap.GeneralPurposeAllocator(.{ .thread_safe = true }){};` the whole time.
I will look more into the double free tomorrow.

**Comment by mookums** [comment]
@Bob-van, didn't see this earlier!

It should be a fairly minimal performance hit (~1-2%). I'll try to benchmark and profile it at some point and get some better data regarding the impact.

**Comment by Bob-van** [comment]
I have to say i love your work so far, and have been enjoying zzz on multiple projects already.

Also i played around Tardy a bit, trying to make backend for "statefull" servers that manage a lot of living connections.
Its a bit sloppy work so far, but i wanted to ask if there is any intend to make "corutine" styled multi-threaded scheduler for Tardy since now there is only entry point for each thread and no cross thread scheduling (or did i miss something?).

Once again, thanks for all the work you do ❤️

**Comment by mookums** [comment]
When you create the initial Tardy instance, you get to choose how many threads will be spawned (the `threading` parameter). Each thread gets its own runtime and that `tardy.entry` runs at the start of every runtime. If you need to do cross-threaded work, you can try using the Tardy Channels which allows you to send data safely across runtimes. It is still pretty experimental but it might do what you need.

No promises but I'll probably experiment with a multithreaded scheduler (for work-stealing on certain workloads) but coroutines are probably out of scope.

**Comment by mookums** [comment]
@Bob-van 

Hi, just wanted to give you an update. Recently, tardy has changed to utilize a coroutine (`Frame`) style as it provides better performance characteristics in certain workloads that matter to me. Each runtime is still only thread-local but this is purposeful as it allows for more consistent and generally better performance characteristics.

Currently working on writing better channels so that spreading multi-thread workloads across Tardy is more realistic.
